perfume(essencial_exclusivo,essencial,femenino,104100,alta).
perfume(essencial_atrai,essencial,femenino,104100,alta).
perfume(essencial_unico,essencial,femenino,125000,alta).
perfume(essencial_mirra,essencial,femenino,104100,alta).
perfume(luna_divina,luna,femenino,75500,moderada).
perfume(luna_clasico,luna,femenino,75500,moderada).
perfume(luna_absoluta,luna,femenino,75500,moderada).
perfume(luna_radiante,luna,femenino,75500,moderada).
perfume(luna_intenso,luna,femenino,79100,alta).
perfume(luna_atitude,luna,femenino,79100,alta).
perfume(una_clasico,una,femenino,112800,alta).
perfume(una_art,una,femenino,112800,alta).
perfume(una_celebrar,una,femenino,112800,alta).
perfume(ilia_clasico,ilia,femenino,79100,alta).
perfume(ilia_secreto,ilia,femenino,79100,alta).
perfume(humor_primeiro,humor,femenino,61400,moderada).
perfume(humor_proprio,humor,femenino,61400,moderada).
perfume(humor_beijo,humor,femenino,61400,moderada).
perfume(kaiak_sonar,kaiak,femenino,64000,moderada).
perfume(kaiak_clasico,kaiak,femenino,64000,moderada).
perfume(kaiak_oceano,kaiak,femenino,64000,moderada).
perfume(kaiak_aventura,kaiak,femenino,64000,moderada).
perfume(kaiak_aero,kaiak,femenino,64000,moderada).
perfume(kaiak_ultra,kaiak,femenino,64000,moderada).
perfume(kriska_clasico,kriska,femenino,51500,moderada).
perfume(kriska_shock,kriska,femenino,51500,moderada).
perfume(kriska_jeans,kriska,femenino,51500,moderada).
perfume(kriska_drama,kriska,femenino,51500,alta).
perfume(frescor_acai,frescor,femenino,46400,leve).
perfume(frescor_maracuya,frescor,femenino,46400,leve).
perfume(frescor_pitanga,frescor,femenino,46400,leve).
perfume(frescor_castaña,frescor,femenino,46400,leve).
perfume(frescor_pitanga_preta,frescor,femenino,46400,leve).
perfume(frescor_cacao,frescor,femenino,46400,leve).
nota_olfativa(frescor_pitanga,salida,aceite_de_hoja_de_pitanga).
nota_olfativa(frescor_pitanga,salida,aceite_de_lima).
nota_olfativa(frescor_pitanga,salida,aceite_de_mandarina).
nota_olfativa(frescor_pitanga,salida,aceite_de_naranja).
nota_olfativa(kaiak_aero,salida,acorde_citrico).
nota_olfativa(luna_atitude,corazon,acorde_flor_de_metamorfosis).
nota_olfativa(frescor_pitanga,salida,albahaca).
nota_olfativa(kaiak_sonar,salida,algas).
nota_olfativa(kaiak_oceano,salida,algas_marinas).
nota_olfativa(frescor_acai,salida,almendra).
nota_olfativa(kriska_clasico,fondo,musk).
nota_olfativa(kriska_jeans,fondo,musk).
nota_olfativa(frescor_cacao,fondo,musk).
nota_olfativa(essencial_exclusivo,fondo,ambar).
nota_olfativa(essencial_mirra,fondo,ambar).
nota_olfativa(luna_clasico,fondo,ambar).
nota_olfativa(una_celebrar,fondo,ambar).
nota_olfativa(ilia_clasico,fondo,ambar).
nota_olfativa(humor_primeiro,fondo,ambar).
nota_olfativa(kaiak_sonar,fondo,ambar).
nota_olfativa(kaiak_clasico,fondo,ambar).
nota_olfativa(kaiak_aventura,fondo,ambar).
nota_olfativa(kriska_jeans,fondo,ambar).
nota_olfativa(kriska_jeans,corazon,angelica).
nota_olfativa(frescor_maracuya,salida,anis).
nota_olfativa(frescor_cacao,salida,anis).
nota_olfativa(kriska_clasico,fondo,benjoin).
nota_olfativa(essencial_atrai,fondo,benjoin).
nota_olfativa(essencial_atrai,salida,bergamota).
nota_olfativa(una_clasico,salida,bergamota).
nota_olfativa(una_art,salida,bergamota).
nota_olfativa(una_celebrar,salida,bergamota).
nota_olfativa(humor_primeiro,salida,bergamota).
nota_olfativa(kaiak_clasico,salida,bergamota).
nota_olfativa(kaiak_aventura,salida,bergamota).
nota_olfativa(kriska_clasico,salida,bergamota).
nota_olfativa(kriska_jeans,salida,bergamota).
nota_olfativa(frescor_maracuya,salida,bergamota).
nota_olfativa(frescor_pitanga,salida,bergamota).
nota_olfativa(frescor_castaña,salida,bergamota).
nota_olfativa(kaiak_sonar,fondo,breu_branco).
nota_olfativa(humor_beijo,fondo,cacao).
nota_olfativa(humor_beijo,salida,canela).
nota_olfativa(kriska_shock,fondo,caramelo).
nota_olfativa(essencial_unico,salida,cardamomo).
nota_olfativa(humor_beijo,salida,cardamomo).
nota_olfativa(kriska_clasico,salida,cardamomo).
nota_olfativa(frescor_cacao,corazon,cardamomo).
nota_olfativa(una_art,fondo,cashmeran).
nota_olfativa(kaiak_oceano,fondo,cashmeran).
nota_olfativa(kaiak_aero,fondo,cashmeran).
nota_olfativa(kaiak_ultra,fondo,cashmeran).
nota_olfativa(luna_atitude,salida,casis).
nota_olfativa(humor_primeiro,salida,casis).
nota_olfativa(kaiak_clasico,salida,casis).
nota_olfativa(frescor_pitanga,corazon,casis).
nota_olfativa(essencial_unico,fondo,cedro).
nota_olfativa(essencial_mirra,fondo,cedro).
nota_olfativa(luna_clasico,fondo,cedro).
nota_olfativa(luna_absoluta,fondo,cedro).
nota_olfativa(luna_intenso,fondo,cedro).
nota_olfativa(una_clasico,fondo,cedro).
nota_olfativa(ilia_secreto,fondo,cedro).
nota_olfativa(humor_proprio,fondo,cedro).
nota_olfativa(kriska_clasico,fondo,cedro).
nota_olfativa(kriska_jeans,fondo,cedro).
nota_olfativa(kriska_drama,fondo,cedro).
nota_olfativa(frescor_maracuya,fondo,cedro).
nota_olfativa(humor_proprio,salida,cereza_en_almibar).
nota_olfativa(frescor_cacao,corazon,chocolate).
nota_olfativa(luna_absoluta,salida,ciruela).
nota_olfativa(humor_beijo,corazon,ciruela).
nota_olfativa(luna_atitude,fondo,complejo_ambarado).
nota_olfativa(kaiak_oceano,fondo,complejo_ambarado).
nota_olfativa(kaiak_aero,fondo,complejo_ambarado).
nota_olfativa(luna_intenso,fondo,complejo_de_musk).
nota_olfativa(essencial_oud,fondo,copaiba).
nota_olfativa(essencial_unico,fondo,copaiba).
nota_olfativa(ilia_clasico,fondo,cumaru).
nota_olfativa(humor_beijo,fondo,cumaru).
nota_olfativa(kaiak_ultra,fondo,cumaru).
nota_olfativa(frescor_acai,fondo,cumaru).
nota_olfativa(frescor_castaña,fondo,cumaru).
nota_olfativa(kriska_clasico,corazon,damasco).
nota_olfativa(essencial_oud,salida,durazno).
nota_olfativa(luna_intenso,salida,durazno).
nota_olfativa(frescor_pitanga,corazon,durazno).
nota_olfativa(kaiak_ultra,salida,estoraque).
nota_olfativa(kriska_jeans,corazon,flor_de_iris).
nota_olfativa(humor_primeiro,corazon,flor_de_macadamia).
nota_olfativa(luna_intenso,corazon,flor_de_naranjo).
nota_olfativa(una_celebrar,corazon,flor_de_naranjo).
nota_olfativa(luna_radiante,corazon,flor_de_paramela).
nota_olfativa(kaiak_oceano,corazon,floral_acuoso).
nota_olfativa(ilia_clasico,salida,flores_blancas).
nota_olfativa(luna_divina,salida,frambuesa).
nota_olfativa(kriska_shock,salida,frambuesa).
nota_olfativa(essencial_unico,corazon,fresia).
nota_olfativa(ilia_secreto,corazon,fresia).
nota_olfativa(kaiak_oceano,salida,frutal_acuoso).
nota_olfativa(luna_atitude,salida,frutilla).
nota_olfativa(una_clasico,salida,frutilla).
nota_olfativa(humor_proprio,salida,frutilla).
nota_olfativa(kriska_clasico,corazon,frutilla).
nota_olfativa(luna_clasico,salida,frutos_rojos).
nota_olfativa(luna_absoluta,salida,frutos_rojos).
nota_olfativa(ilia_clasico,salida,frutos_rojos).
nota_olfativa(kriska_shock,salida,frutos_rojos).
nota_olfativa(kriska_drama,salida,frutos_rojos).
nota_olfativa(frescor_cacao,salida,gardenia).
nota_olfativa(kriska_clasico,corazon,geranio).
nota_olfativa(luna_intenso,salida,casis).
nota_olfativa(frescor_pitanga_preta,salida,hojas_de_pitanga).
nota_olfativa(luna_absoluta,corazon,hojas_de_violeta).
nota_olfativa(frescor_acai,corazon,hojas_de_violeta).
nota_olfativa(una_art,salida,hojas_verdes).
nota_olfativa(essencial_mirra,fondo,incienso).
nota_olfativa(essencial_unico,salida,ishpink).
nota_olfativa(essencial_oud,corazon,jazmin).
nota_olfativa(essencial_unico,corazon,jazmin).
nota_olfativa(essencial_mirra,corazon,jazmin).
nota_olfativa(luna_clasico,corazon,jazmin).
nota_olfativa(luna_intenso,corazon,jazmin).
nota_olfativa(luna_atitude,corazon,jazmin).
nota_olfativa(una_clasico,corazon,jazmin).
nota_olfativa(una_art,corazon,jazmin).
nota_olfativa(ilia_clasico,corazon,jazmin).
nota_olfativa(humor_primeiro,corazon,jazmin).
nota_olfativa(humor_proprio,corazon,jazmin).
nota_olfativa(humor_beijo,corazon,jazmin).
nota_olfativa(kaiak_sonar,corazon,jazmin).
nota_olfativa(kaiak_clasico,corazon,jazmin).
nota_olfativa(kaiak_oceano,corazon,jazmin).
nota_olfativa(kaiak_aventura,corazon,jazmin).
nota_olfativa(kaiak_ultra,corazon,jazmin).
nota_olfativa(kriska_clasico,corazon,jazmin).
nota_olfativa(kriska_jeans,corazon,jazmin).
nota_olfativa(frescor_maracuya,corazon,jazmin).
nota_olfativa(frescor_pitanga,corazon,jazmin).
nota_olfativa(frescor_castaña,corazon,jazmin).
nota_olfativa(frescor_pitanga_preta,corazon,jazmin).
nota_olfativa(una_celebrar,salida,jengibre).
nota_olfativa(humor_beijo,salida,jengibre).
nota_olfativa(kriska_jeans,corazon,jengibre).
nota_olfativa(kaiak_aero,corazon,lavanda).
nota_olfativa(kaiak_ultra,corazon,lavanda).
nota_olfativa(kriska_clasico,salida,lavanda).
nota_olfativa(kriska_jeans,salida,limon).
nota_olfativa(frescor_pitanga,salida,limon).
nota_olfativa(kaiak_sonar,corazon,lirio).
nota_olfativa(frescor_castaña,corazon,lirio).
nota_olfativa(humor_primeiro,corazon,muguet).
nota_olfativa(kriska_jeans,corazon,muguet).
nota_olfativa(essencial_exclusivo,corazon,magnolia).
nota_olfativa(ilia_secreto,corazon,magnolia).
nota_olfativa(kaiak_sonar,corazon,magnolia).
nota_olfativa(kriska_shock,fondo,maltol).
nota_olfativa(essencial_exclusivo,salida,mandarina).
nota_olfativa(essencial_mirra,salida,mandarina).
nota_olfativa(ilia_secreto,salida,mandarina).
nota_olfativa(humor_beijo,salida,mandarina).
nota_olfativa(kaiak_sonar,salida,mandarina).
nota_olfativa(kriska_drama,salida,mandarina).
nota_olfativa(frescor_castaña,salida,mandarina).
nota_olfativa(kriska_drama,salida,manzana).
nota_olfativa(frescor_maracuya,salida,manzana).
nota_olfativa(frescor_maracuya,corazon,maracuya).
nota_olfativa(kaiak_sonar,salida,menta).
nota_olfativa(essencial_mirra,fondo,mirra).
nota_olfativa(luna_atitude,salida,mora).
nota_olfativa(una_clasico,salida,mora_salvaje).
nota_olfativa(essencial_atrai,corazon,muguet).
nota_olfativa(luna_radiante,corazon,muguet).
nota_olfativa(luna_intenso,corazon,muguet).
nota_olfativa(luna_atitude,corazon,muguet).
nota_olfativa(una_celebrar,corazon,muguet).
nota_olfativa(kaiak_clasico,corazon,muguet).
nota_olfativa(kriska_clasico,corazon,muguet).
nota_olfativa(frescor_pitanga_preta,corazon,muguet).
nota_olfativa(luna_divina,fondo,musgo).
nota_olfativa(luna_atitude,fondo,musgo).
nota_olfativa(frescor_pitanga,fondo,musgo).
nota_olfativa(essencial_exclusivo,fondo,musk).
nota_olfativa(luna_absoluta,fondo,musk).
nota_olfativa(luna_atitude,fondo,musk).
nota_olfativa(ilia_secreto,fondo,musk).
nota_olfativa(humor_primeiro,fondo,musk).
nota_olfativa(kaiak_clasico,fondo,musk).
nota_olfativa(kaiak_aventura,fondo,musk).
nota_olfativa(kriska_shock,fondo,musk).
nota_olfativa(frescor_maracuya,fondo,musk).
nota_olfativa(frescor_pitanga,fondo,musk).
nota_olfativa(frescor_castaña,fondo,musk).
nota_olfativa(frescor_pitanga_preta,fondo,musk).
nota_olfativa(essencial_exclusivo,salida,naranja).
nota_olfativa(humor_primeiro,salida,naranja).
nota_olfativa(kriska_jeans,salida,naranja).
nota_olfativa(frescor_cacao,salida,naranja).
nota_olfativa(luna_radiante,salida,naranja_amarga).
nota_olfativa(nombre,tipo,nota).
nota_olfativa(kaiak_sonar,salida,notas_acuosas).
nota_olfativa(una_celebrar,salida,notas_citricas).
nota_olfativa(kriska_shock,fondo,notas_gourmand).
nota_olfativa(kaiak_aventura,salida,notas_verdes).
nota_olfativa(kriska_clasico,salida,notas_verdes).
nota_olfativa(kriska_jeans,salida,notas_verdes).
nota_olfativa(kriska_drama,corazon,nueces_caramelizadas).
nota_olfativa(kriska_shock,corazon,orquidea).
nota_olfativa(luna_absoluta,corazon,orquidea_negra).
nota_olfativa(essencial_oud,fondo,oud).
nota_olfativa(kaiak_oceano,salida,pataqueira).
nota_olfativa(essencial_mirra,fondo,patchouli).
nota_olfativa(luna_divina,fondo,patchouli).
nota_olfativa(luna_clasico,fondo,patchouli).
nota_olfativa(luna_absoluta,fondo,patchouli).
nota_olfativa(luna_radiante,fondo,patchouli).
nota_olfativa(luna_intenso,fondo,patchouli).
nota_olfativa(luna_atitude,fondo,patchouli).
nota_olfativa(una_clasico,fondo,patchouli).
nota_olfativa(una_art,fondo,patchouli).
nota_olfativa(kaiak_sonar,fondo,patchouli).
nota_olfativa(kriska_clasico,fondo,patchouli).
nota_olfativa(luna_divina,corazon,peonia).
nota_olfativa(una_clasico,corazon,peonia).
nota_olfativa(una_art,corazon,peonia).
nota_olfativa(kaiak_sonar,corazon,peonia).
nota_olfativa(kaiak_aventura,corazon,peonia).
nota_olfativa(kaiak_aero,corazon,peonia).
nota_olfativa(frescor_acai,corazon,peonia).
nota_olfativa(kriska_shock,corazon,peonia_rosa).
nota_olfativa(essencial_atrai,salida,pera).
nota_olfativa(luna_intenso,salida,pera).
nota_olfativa(luna_atitude,salida,pera).
nota_olfativa(ilia_secreto,salida,pera).
nota_olfativa(humor_primeiro,salida,pera).
nota_olfativa(humor_beijo,salida,pera).
nota_olfativa(kaiak_sonar,salida,pera).
nota_olfativa(kaiak_aero,salida,pera).
nota_olfativa(frescor_acai,salida,pera).
nota_olfativa(essencial_mirra,corazon,pimienta).
nota_olfativa(essencial_unico,salida,pimienta_negra).
nota_olfativa(essencial_mirra,salida,pimienta_negra).
nota_olfativa(essencial_oud,salida,pimienta_rosa).
nota_olfativa(essencial_atrai,salida,pimienta_rosa).
nota_olfativa(essencial_mirra,salida,pimienta_rosa).
nota_olfativa(luna_divina,salida,pimienta_rosa).
nota_olfativa(luna_clasico,salida,pimienta_rosa).
nota_olfativa(luna_radiante,salida,pimienta_rosa).
nota_olfativa(luna_atitude,salida,pimienta_rosa).
nota_olfativa(kaiak_aventura,salida,pimienta_rosa).
nota_olfativa(kaiak_aero,salida,pimienta_rosa).
nota_olfativa(kriska_shock,salida,pimienta_rosa).
nota_olfativa(kaiak_ultra,salida,piper).
nota_olfativa(kaiak_ultra,salida,pitanga).
nota_olfativa(frescor_pitanga_preta,salida,pitanga_preta).
nota_olfativa(una_clasico,salida,pomelo).
nota_olfativa(frescor_pitanga,salida,pomelo).
nota_olfativa(ilia_clasico,salida,pomelo_rosado).
nota_olfativa(essencial_atrai,fondo,praline).
nota_olfativa(luna_divina,fondo,priprioca).
nota_olfativa(luna_radiante,fondo,priprioca).
nota_olfativa(essencial_oud,corazon,rosa).
nota_olfativa(essencial_exclusivo,corazon,rosa).
nota_olfativa(essencial_atrai,corazon,rosa).
nota_olfativa(essencial_unico,corazon,rosa).
nota_olfativa(essencial_mirra,corazon,rosa).
nota_olfativa(luna_divina,corazon,rosa).
nota_olfativa(luna_clasico,corazon,rosa).
nota_olfativa(luna_absoluta,corazon,rosa).
nota_olfativa(luna_intenso,corazon,rosa).
nota_olfativa(luna_atitude,corazon,rosa).
nota_olfativa(una_clasico,corazon,rosa).
nota_olfativa(una_art,corazon,rosa).
nota_olfativa(ilia_clasico,corazon,rosa).
nota_olfativa(ilia_secreto,corazon,rosa).
nota_olfativa(humor_proprio,corazon,rosa).
nota_olfativa(kaiak_clasico,corazon,rosa).
nota_olfativa(kaiak_aventura,corazon,rosa).
nota_olfativa(kaiak_ultra,corazon,rosa).
nota_olfativa(kriska_clasico,corazon,rosa).
nota_olfativa(kriska_jeans,corazon,rosa).
nota_olfativa(frescor_maracuya,corazon,rosa).
nota_olfativa(frescor_castaña,corazon,rosa).
nota_olfativa(frescor_pitanga_preta,corazon,rosa).
nota_olfativa(kaiak_aero,corazon,salvia).
nota_olfativa(essencial_exclusivo,fondo,sandalo).
nota_olfativa(luna_intenso,fondo,sandalo).
nota_olfativa(una_clasico,fondo,sandalo).
nota_olfativa(una_celebrar,fondo,sandalo).
nota_olfativa(humor_primeiro,fondo,sandalo).
nota_olfativa(humor_beijo,fondo,sandalo).
nota_olfativa(kaiak_clasico,fondo,sandalo).
nota_olfativa(kaiak_oceano,fondo,sandalo).
nota_olfativa(kaiak_aventura,fondo,sandalo).
nota_olfativa(kaiak_ultra,fondo,sandalo).
nota_olfativa(kriska_jeans,fondo,sandalo).
nota_olfativa(kriska_drama,fondo,sandalo).
nota_olfativa(frescor_acai,fondo,sandalo).
nota_olfativa(frescor_pitanga,fondo,sandalo).
nota_olfativa(frescor_pitanga_preta,fondo,sandalo).
nota_olfativa(frescor_cacao,corazon,sandalo).
nota_olfativa(luna_atitude,fondo,cumaru).
nota_olfativa(kriska_jeans,salida,pomelo).
nota_olfativa(essencial_atrai,fondo,vainilla).
nota_olfativa(luna_intenso,fondo,vainilla).
nota_olfativa(una_art,fondo,vainilla).
nota_olfativa(una_celebrar,fondo,vainilla).
nota_olfativa(ilia_clasico,fondo,vainilla).
nota_olfativa(ilia_secreto,fondo,vainilla).
nota_olfativa(humor_proprio,fondo,vainilla).
nota_olfativa(humor_beijo,fondo,vainilla).
nota_olfativa(kriska_clasico,fondo,vainilla).
nota_olfativa(kriska_shock,corazon,vainilla).
nota_olfativa(kriska_shock,fondo,vainilla).
nota_olfativa(kriska_drama,fondo,vainilla).
nota_olfativa(frescor_cacao,fondo,vainilla).
nota_olfativa(essencial_unico,fondo,vetiver).
nota_olfativa(essencial_mirra,fondo,vetiver).
nota_olfativa(kaiak_sonar,fondo,vetiver).
nota_olfativa(kaiak_aero,fondo,vetiver).
nota_olfativa(frescor_cacao,fondo,vetiver).
nota_olfativa(essencial_atrai,corazon,violeta).
nota_olfativa(luna_clasico,corazon,violeta).
nota_olfativa(luna_intenso,corazon,violeta).
nota_olfativa(kaiak_sonar,corazon,violeta).
nota_olfativa(kaiak_ultra,corazon,violeta).
nota_olfativa(kaiak_oceano,corazon,ylang).
clasifica_nota(aceite_de_hoja_de_pitanga,citrico).
clasifica_nota(aceite_de_lima,citrico).
clasifica_nota(aceite_de_mandarina,citrico).
clasifica_nota(aceite_de_naranja,citrico).
clasifica_nota(acorde_citrico,citrico).
clasifica_nota(acorde_flor_de_metamorfosis,chipre).
clasifica_nota(albahaca,aromatico).
clasifica_nota(algas,acuatico).
clasifica_nota(algas_marinas,acuatico).
clasifica_nota(almendra,gourmand).
clasifica_nota(musk,limpio).
clasifica_nota(ambar,oriental).
clasifica_nota(angelica,herbal).
clasifica_nota(anis,especiado).
clasifica_nota(benjoin,dulce).
clasifica_nota(bergamota,citrico).
clasifica_nota(breu_branco,citrico).
clasifica_nota(cacao,gourmand).
clasifica_nota(canela,especiado).
clasifica_nota(caramelo,gourmand).
clasifica_nota(cardamomo,especiado).
clasifica_nota(cashmeran,amaderado).
clasifica_nota(casis,frutal).
clasifica_nota(cedro,amaderado).
clasifica_nota(cereza_en_almibar,gourmand).
clasifica_nota(chocolate,gourmand).
clasifica_nota(ciruela,frutal).
clasifica_nota(complejo_ambarado,oriental).
clasifica_nota(complejo_de_musk,limpio).
clasifica_nota(copaiba,amaderado).
clasifica_nota(cumaru,dulce).
clasifica_nota(damasco,frutal).
clasifica_nota(durazno,frutal).
clasifica_nota(estoraque,aromatico).
clasifica_nota(flor_de_iris,amaderado).
clasifica_nota(flor_de_macadamia,floral).
clasifica_nota(flor_de_naranjo,floral).
clasifica_nota(flor_de_paramela,floral).
clasifica_nota(floral_acuoso,floral).
clasifica_nota(flores_blancas,floral).
clasifica_nota(frambuesa,frutal).
clasifica_nota(fresia,floral).
clasifica_nota(frutal_acuoso,frutal).
clasifica_nota(frutilla,frutal).
clasifica_nota(frutos_rojos,frutal).
clasifica_nota(gardenia,floral).
clasifica_nota(geranio,floral).
clasifica_nota(hojas_de_pitanga,aromatico).
clasifica_nota(hojas_verdes,aromatico).
clasifica_nota(incienso,oriental).
clasifica_nota(ishpink,especiado).
clasifica_nota(jazmin,floral).
clasifica_nota(jengibre,especiado).
clasifica_nota(lavanda,aromatico).
clasifica_nota(limon,citrico).
clasifica_nota(lirio,floral).
clasifica_nota(magnolia,floral).
clasifica_nota(maltol,gourmand).
clasifica_nota(mandarina,citrico).
clasifica_nota(manzana,frutal).
clasifica_nota(maracuya,frutal).
clasifica_nota(menta,aromatico).
clasifica_nota(mirra,amaderado).
clasifica_nota(mora,frutal).
clasifica_nota(mora_salvaje,frutal).
clasifica_nota(muguet,floral).
clasifica_nota(musgo,chipre).
clasifica_nota(naranja,citrico).
clasifica_nota(naranja_amarga,citrico).
clasifica_nota(notas_acuosas,acuatico).
clasifica_nota(notas_citricas,citrico).
clasifica_nota(notas_gourmand,gourmand).
clasifica_nota(notas_verdes,aromatico).
clasifica_nota(nueces_caramelizadas,gourmand).
clasifica_nota(orquidea,floral).
clasifica_nota(orquidea_negra,floral).
clasifica_nota(oud,amaderado).
clasifica_nota(pataqueira,aromatico).
clasifica_nota(patchouli,amaderado).
clasifica_nota(peonia,floral).
clasifica_nota(peonia_rosa,floral).
clasifica_nota(pera,frutal).
clasifica_nota(pimienta,especiado).
clasifica_nota(pimienta_negra,especiado).
clasifica_nota(pimienta_negra,especiado).
clasifica_nota(pimienta_rosa,especiado).
clasifica_nota(piper,especiado).
clasifica_nota(pitanga,frutal).
clasifica_nota(pitanga_preta,frutal).
clasifica_nota(pomelo,citrico).
clasifica_nota(pomelo_rosado,citrico).
clasifica_nota(praline,gourmand).
clasifica_nota(priprioca,amaderado).
clasifica_nota(rosa,floral).
clasifica_nota(salvia,aromatico).
clasifica_nota(sandalo,amaderado).
clasifica_nota(vainilla,gourmand).
clasifica_nota(vetiver,amaderado).
clasifica_nota(violeta,floral).
clasifica_nota(ylang,floral).
